import {
  // Hidden services' icons: WebIcon, SocialIcon, AdsIcon, SeoIcon, MailIcon, ContentIcon
  AiIcon, ErpIcon, VideoIcon, GearIcon, SnowIcon, ThermoIcon, CubeIcon, FlameIcon,
} from './icons';

// ─── Services ─────────────────────────────────────────────────────────────────
// First 6 show by default; the rest reveal behind "Show more".
export const SERVICES = [
  // Hidden: services no longer offered (Web Design, Social Media, Meta & Google Ads,
  // AI SEO, Email Marketing, Content Creation). Uncomment to bring one back.
  // {
  //   num: '01',
  //   name: 'Web Design',
  //   color: '#7c5cff',
  //   gradient: 'linear-gradient(90deg,#7c5cff,#a07cff)',
  //   colorLight: '#8b3fd6',
  //   gradientLight: 'linear-gradient(90deg,#8b3fd6,#ab6ef0)',
  //   description: 'Conversion-first websites and landing pages designed to turn visitors into paying customers.',
  //   href: '#portfolio',
  //   Icon: WebIcon,
  // },
  // {
  //   num: '02',
  //   name: 'Social Media',
  //   color: '#ff4d9d',
  //   gradient: 'linear-gradient(90deg,#ff4d9d,#ff7ab8)',
  //   colorLight: '#db2777',
  //   gradientLight: 'linear-gradient(90deg,#db2777,#f25ba0)',
  //   description: 'Scroll-stopping content and community management that grows your audience on every platform.',
  //   href: '#portfolio',
  //   Icon: SocialIcon,
  // },
  // {
  //   num: '03',
  //   name: 'Meta & Google Ads',
  //   color: '#ff8c1e',
  //   gradient: 'linear-gradient(90deg,#ff8c1e,#ffb14d)',
  //   colorLight: '#d97706',
  //   gradientLight: 'linear-gradient(90deg,#d97706,#f59e3c)',
  //   description: 'Performance ad campaigns on Meta and Google engineered for a measurable return on every dollar.',
  //   href: '#portfolio',
  //   Icon: AdsIcon,
  // },
  // {
  //   num: '04',
  //   name: 'AI SEO',
  //   color: '#1e9bff',
  //   gradient: 'linear-gradient(90deg,#1e9bff,#5bc0ff)',
  //   colorLight: '#2c46d8',
  //   gradientLight: 'linear-gradient(90deg,#2c46d8,#5a72f0)',
  //   description: 'Rank on Google, ChatGPT, and Perplexity, traditional SEO meets AI search optimization.',
  //   href: '#portfolio',
  //   Icon: SeoIcon,
  // },
  // {
  //   num: '07',
  //   name: 'Email Marketing',
  //   color: '#f5b21a',
  //   gradient: 'linear-gradient(90deg,#f5b21a,#ffce5c)',
  //   colorLight: '#d97706',
  //   gradientLight: 'linear-gradient(90deg,#d97706,#f59e3c)',
  //   description: 'Lifecycle emails and flows that nurture leads and turn one-time buyers into regulars.',
  //   href: '#portfolio',
  //   Icon: MailIcon,
  // },
  // {
  //   num: '08',
  //   name: 'Content Creation',
  //   color: '#c879ff',
  //   gradient: 'linear-gradient(90deg,#c879ff,#dba6ff)',
  //   colorLight: '#8b3fd6',
  //   gradientLight: 'linear-gradient(90deg,#8b3fd6,#ab6ef0)',
  //   description: 'On-brand video, graphics and copy produced at scale with an AI-assisted workflow.',
  //   href: '#portfolio',
  //   Icon: ContentIcon,
  // },
  {
    // ── Client copy: Core Service Portfolios ──
    num: '01',
    name: 'HVAC & Chiller Plant O&M',
    color: '#4fcdee',
    gradient: 'linear-gradient(90deg,#4fcdee,#8ae0f5)',
    colorLight: '#0e7ea3',
    gradientLight: 'linear-gradient(90deg,#0e7ea3,#30b4d8)',
    description: 'Continuous, energy-optimized climate control utilizing precision water chemistry treatment, tube descaling, and strict refrigerant management.',
    href: '/operations-maintenance',
    Icon: ThermoIcon,
  },
  {
    num: '02',
    name: 'Industrial Refrigeration O&M',
    color: '#a878ff',
    gradient: 'linear-gradient(90deg,#a878ff,#c8a8ff)',
    colorLight: '#7c3aed',
    gradientLight: 'linear-gradient(90deg,#7c3aed,#a078f0)',
    description: 'Ultra-low temperature control loops, multi-stage compressor overhauls, and strict thermal boundary sealing for critical cold chains.',
    href: '/industrial-refrigeration',
    Icon: SnowIcon,
  },
  {
    num: '03',
    name: 'SP.ICE Thermal Storage Systems',
    color: '#38bdf8',
    gradient: 'linear-gradient(90deg,#38bdf8,#7dd3fc)',
    colorLight: '#0369a1',
    gradientLight: 'linear-gradient(90deg,#0369a1,#0ea5e9)',
    description: 'Powered by advanced German technology. Shift 100% of your peak daytime cooling load to economical off-peak night hours using high-density encapsulated ice matrices.',
    href: '/sp-ice-tes',
    Icon: CubeIcon,
  },
  {
    num: '04',
    name: 'Full-Spectrum MEP Services',
    color: '#c8f31d',
    gradient: 'linear-gradient(90deg,#c8f31d,#dcff6a)',
    colorLight: '#142196',
    gradientLight: 'linear-gradient(90deg,#142196,#2c46d8)',
    description: 'Turnkey management of complex low-voltage electrical distribution networks, hydraulic pipe balancing, and smart building automation controls.',
    href: '/mep-engineering',
    Icon: GearIcon,
  },
  {
    num: '05',
    name: 'Life Safety & Firefighting Engineering',
    color: '#ff8c1e',
    gradient: 'linear-gradient(90deg,#ff8c1e,#ffb14d)',
    colorLight: '#d97706',
    gradientLight: 'linear-gradient(90deg,#d97706,#f59e3c)',
    description: 'Rigorous compliance testing of high-pressure fire pumps, addressable detection networks, and clean-agent gas suppression systems.',
    href: '/fire-life-safety',
    Icon: FlameIcon,
  },
  // ── AI side ──
  {
    num: '06',
    name: 'AI Assistant & Automation',
    color: '#10b981',
    gradient: 'linear-gradient(90deg,#10b981,#3ed9a4)',
    colorLight: '#2f9e44',
    gradientLight: 'linear-gradient(90deg,#2f9e44,#51c46a)',
    description: 'Custom AI systems built around your workflow, like turning 100 daily emails into the few that matter, sorted, with replies drafted.',
    href: '/ai-automation',
    Icon: AiIcon,
  },
  {
    num: '07',
    name: 'ERP Services & Development',
    color: '#ff4d4d',
    gradient: 'linear-gradient(90deg,#ff4d4d,#ff7a7a)',
    colorLight: '#db2777',
    gradientLight: 'linear-gradient(90deg,#db2777,#f25ba0)',
    description: 'End-to-end SAP implementation and support, Finance, Procurement, HR, Sales and Analytics, by KSA’s leading SAP partner.',
    href: '/erp-development',
    Icon: ErpIcon,
  },
  {
    num: '08',
    name: 'AI Animated Videos',
    color: '#ff5c8a',
    gradient: 'linear-gradient(90deg,#ff5c8a,#ff8fb0)',
    colorLight: '#db2777',
    gradientLight: 'linear-gradient(90deg,#db2777,#f25ba0)',
    description: 'AI-produced corporate intros, explainers and animated videos, on-brand and delivered fast in Arabic and English.',
    href: '/ai-video',
    Icon: VideoIcon,
  },
];

export const INITIAL_COUNT = 6;
