// ─── Searchable site index (knowledge base) ──────────────────────────────────
// A flat, client-side index of everything on the site. The "Ask AI" bar searches
// this. Each entry carries a deep `href` (page + section) so "Read more" can open
// the exact place in a new tab. In production this could be swapped for a real
// API / vector search - the UI contract (an array of these items) stays the same.
export const SITE_INDEX = [
  // ── Company / overview ──
  {
    id: 'about-safehands',
    category: 'Company',
    title: 'About SafeHands',
    description: 'SafeHands is a technology and digital partner helping businesses transform with ERP, custom software, AI and marketing, bespoke solutions delivered across Saudi Arabia & APAC.',
    keywords: ['safehands', 'safe hands', 'company', 'about', 'who', 'overview', 'agency', 'partner'],
    href: '/#about',
  },
  {
    id: 'locations',
    category: 'Company',
    title: 'Riyadh · Saudi Arabia',
    description: 'Based in Riyadh and serving clients across Saudi Arabia and the APAC region.',
    keywords: ['riyadh', 'saudi', 'arabia', 'ksa', 'location', 'where', 'office', 'apac', 'region'],
    href: '/#exd',
  },
  {
    id: 'contact',
    category: 'Company',
    title: 'Contact Us',
    description: 'Get in touch with the SafeHands team, start a conversation about your project.',
    keywords: ['contact', 'email', 'call', 'talk', 'reach', 'quote', 'enquiry', 'get in touch'],
    href: '/contact',
  },
  {
    id: 'get-started',
    category: 'Company',
    title: 'Get Started',
    description: 'Kick off your project with a guided onboarding flow built to scope your needs fast.',
    keywords: ['start', 'get started', 'onboarding', 'begin', 'signup', 'project', 'kickoff'],
    href: '/onboarding',
  },
  {
    id: 'portfolio',
    category: 'Company',
    title: 'Portfolio & Work',
    description: 'A look at the projects and results SafeHands has delivered for clients.',
    keywords: ['portfolio', 'work', 'projects', 'case study', 'results', 'examples', 'clients'],
    href: '/#portfolio',
  },

  // ── ERP / SAP / Development ──
  {
    id: 'erp-services',
    category: 'Service',
    title: 'ERP Services',
    description: 'As an emerging ERP System Integrator, SafeHands offers licensing, implementation, support and upgrades for cloud and on-premise platforms, SAP, ETM.Next, Qlik, Jaggaer and Salesforce.',
    keywords: ['erp', 'sap', 'implementation', 'integrator', 'system', 'licensing', 'upgrade', 'cloud', 'on-premise', 'migration', 'etm', 'qlik', 'jaggaer', 'salesforce'],
    href: '/erp-development#erp-services',
  },
  {
    id: 'software-development',
    category: 'Service',
    title: 'Software Development',
    description: 'A full-stack team of developers, designers, architects and project managers building innovative, scalable and secure solutions, web, mobile, IoT and enterprise.',
    keywords: ['software', 'development', 'developer', 'app', 'web', 'mobile', 'ios', 'android', 'php', '.net', 'laravel', 'python', 'java', 'ruby', 'code', 'programming', 'fiori', 'abap'],
    href: '/erp-development#software-development',
  },
  {
    id: 'outsourcing',
    category: 'Service',
    title: 'Outsourcing',
    description: 'Comprehensive outsourcing across IT, digital operations, data entry, ERP maintenance, HRM and finance, so you can focus on core competencies and strategic growth.',
    keywords: ['outsourcing', 'outsource', 'it', 'hrm', 'finance', 'data entry', 'community management', 'maintenance', 'operations', 'staffing'],
    href: '/erp-development#outsourcing',
  },
  {
    id: 'sap-partner',
    category: 'Partnership',
    title: 'SAP Service Provider',
    description: 'SafeHands is a leading SAP service provider in Saudi Arabia and a local partner of BearingPoint.',
    keywords: ['sap', 'platinum', 'partner', 'bearingpoint', 'service provider', 'integrator'],
    href: '/#exd',
  },
  {
    id: 'partner-ecosystem',
    category: 'Partnership',
    title: 'Partner Ecosystem',
    description: 'A unique ecosystem of best-in-class partners, BearingPoint, Jaggaer and Salesforce, for tailored solutions that help your business thrive.',
    keywords: ['partners', 'ecosystem', 'bearingpoint', 'jaggaer', 'salesforce', 'qlik', 'oracle', 'alliance'],
    href: '/#exd',
  },
  {
    id: 'ai-sap',
    category: 'Technology',
    title: 'AI on SAP, Joule & JAI',
    description: 'AI implementations that unlock analytics and intelligence across SAP, ETM.Next, Qlik and Jaggaer, including SAP’s Generative AI, Joule, and Jaggaer’s AI, JAI.',
    keywords: ['joule', 'jai', 'generative ai', 'sap ai', 'jaggaer ai', 'analytics', 'intelligence', 'machine learning'],
    href: '/#exd',
  },
  {
    id: 'digital-transformation',
    category: 'Why Us',
    title: 'Digital Transformation',
    description: 'A vendor-agnostic approach rooted in customer centricity and integrity, full visibility and efficiency through state-of-the-art technology.',
    keywords: ['digital transformation', 'transformation', 'vendor agnostic', 'modernization', 'efficiency', 'visibility'],
    href: '/#exd',
  },

  // ── Marketing & web services ──
  {
    id: 'svc-seo',
    category: 'Service',
    title: 'AI SEO',
    description: 'Rank everywhere people search, Google, ChatGPT and Perplexity. Traditional SEO blended with AI-search optimization so your brand gets found and cited.',
    keywords: ['seo', 'search', 'ranking', 'google', 'chatgpt', 'perplexity', 'visibility', 'organic', 'website'],
    href: '/seo',
  },
  {
    id: 'svc-web',
    category: 'Service',
    title: 'Web Development',
    description: 'High-converting websites on Next.js, WordPress or fully custom code, fast, SEO-ready and built to turn visitors into customers.',
    keywords: ['web', 'website', 'design', 'development', 'nextjs', 'wordpress', 'landing page', 'frontend', 'ui', 'ux'],
    href: '/web-development',
  },
  {
    id: 'svc-social',
    category: 'Service',
    title: 'Social Media',
    description: 'Content, community and paid social that grows your audience and drives conversions across every platform.',
    keywords: ['social', 'instagram', 'tiktok', 'linkedin', 'youtube', 'content', 'community', 'smm'],
    href: '/social-media',
  },
  {
    id: 'svc-paid-ads',
    category: 'Service',
    title: 'Paid Ads',
    description: 'ROI-focused ad campaigns on Meta and Google, full-funnel strategy, creative, targeting and continuous optimization.',
    keywords: ['ads', 'ppc', 'google ads', 'meta ads', 'paid', 'campaign', 'roi', 'advertising'],
    href: '/paid-ads',
  },
  {
    id: 'svc-solutions',
    category: 'Service',
    title: 'Solutions & Pricing',
    description: 'Explore the full range of SafeHands services with clear scope and pricing for each.',
    keywords: ['solutions', 'pricing', 'packages', 'services', 'cost', 'price', 'plans'],
    href: '/solutions',
  },

  // ── AI products ──
  {
    id: 'svc-ai-employees',
    category: 'Service',
    title: 'AI Employees',
    description: 'AI employees that run your operations 24/7, trained on your business and managed by licensed experts.',
    keywords: ['ai employee', 'agent', 'operator', 'automation', 'workflow', 'autonomous', 'assistant'],
    href: '/ai-employees',
  },
  {
    id: 'tech-maya',
    category: 'Technology',
    title: 'Maya, AI Strategist',
    description: 'A live AI strategist available 24/7, trained on everything SafeHands does, chat or start a voice call.',
    keywords: ['maya', 'ai strategist', 'chat', 'chatbot', 'assistant', 'voice', 'help'],
    href: '/#maya',
  },
  {
    id: 'tech-chatbot',
    category: 'Technology',
    title: 'AI Chatbots & Automations',
    description: 'Custom AI assistants and automations that handle support, qualify leads and book meetings around the clock.',
    keywords: ['chatbot', 'chat', 'conversation', 'ai', 'support', 'lead', 'automation', 'bot'],
    href: '/ai-employees',
  },

  // ── Why us / proof points ──
  {
    id: 'why-ai-first',
    category: 'Why Us',
    title: 'AI-First Approach',
    description: 'AI is the engine underneath every solution we build, not a bolt-on.',
    keywords: ['ai first', 'approach', 'technology', 'engine', 'strategy', 'innovation'],
    href: '/#different',
  },
  {
    id: 'why-results',
    category: 'Why Us',
    title: 'Real, Measurable Results',
    description: 'Real revenue and outcomes, not vanity metrics. Numbers that move your P&L.',
    keywords: ['roi', 'results', 'revenue', 'return', 'growth', 'profit', 'measurable', 'outcomes'],
    href: '/#results',
  },
  {
    id: 'why-experts',
    category: 'Why Us',
    title: 'Certified Experts Only',
    description: 'Every strategist and engineer holds active certifications, no generalists, no interns.',
    keywords: ['certified', 'experts', 'team', 'licensed', 'specialists', 'professionals'],
    href: '/#different',
  },
];
