// ─── Solutions page service cards ─────────────────────────────────────────────
// Colours / gradients are taken straight from the reference design — one accent
// per service, reused for the number, tags, bullets and the "GET STARTED" pill.
export const SOLUTIONS = [
  {
    num: '01',
    tags: 'GOOGLE · CHATGPT · PERPLEXITY · SGE',
    title: 'AI SEO',
    desc: 'Rank everywhere people search — Google, ChatGPT, Perplexity, and Google AI Overviews. We combine traditional SEO with AI search optimization so your brand gets found and cited across every platform.',
    features: [
      'Technical SEO audit & fixes',
      'Link building',
      'AI Overview & Perplexity citations',
      'Keyword research & content strategy',
      'llms.txt & entity SEO',
      'Schema markup & E-E-A-T content',
    ],
    price: 'From $1,500 / mo',
    color: '#1e9bff',
    gradient: 'linear-gradient(90deg,#1e9bff,#5bc0ff)',
  },
  {
    num: '02',
    tags: 'SMM',
    title: 'Social Media Marketing',
    desc: 'From organic content creation to influencer marketing. We manage TikTok, Instagram, LinkedIn, and YouTube with data-driven strategies that grow your brand and drive conversions.',
    features: [
      'Content strategy & calendar',
      'Influencer collaboration',
      'Trend analysis',
      'Creative video production',
      'Community management',
      'Performance reporting',
    ],
    price: 'From $2,500 / mo',
    color: '#ff4d9d',
    gradient: 'linear-gradient(90deg,#ff4d9d,#ff7ab8)',
  },
  {
    num: '03',
    tags: 'PAID ADS',
    title: 'Meta & Google Ads',
    desc: 'ROI-focused paid ad campaigns. We handle full-funnel strategy, creative production, audience targeting, and continuous optimization across Meta and Google.',
    features: [
      'Campaign strategy & setup',
      'Audience research & targeting',
      'Conversion tracking',
      'Ad creative production',
      'A/B testing',
      'Weekly optimization reports',
    ],
    price: 'From $2,000 / mo + ad spend',
    color: '#ff8c1e',
    gradient: 'linear-gradient(90deg,#ff8c1e,#ffb14d)',
  },
  {
    num: '04',
    tags: 'CLAUDE · AI · CHATBOTS',
    title: 'AI Assistants & Automations',
    desc: 'Custom AI assistants deployed on Claude — trained on your business, live 24/7. We handle everything from strategy and build to integration and ongoing optimization.',
    features: [
      'Business needs analysis',
      'Claude / OpenAI deployment',
      'Lead qualification flows',
      'Custom AI assistant design',
      'Platform & CRM integration',
      '24/7 automated support',
    ],
    price: 'Custom pricing',
    color: '#10b981',
    gradient: 'linear-gradient(90deg,#10b981,#3ed9a4)',
  },
  {
    num: '05',
    tags: 'NEXT.JS · WORDPRESS · CUSTOM',
    title: 'Web Design & Development',
    desc: 'High-converting websites built on Next.js, WordPress, or fully custom code. Optimized for speed, SEO, and mobile — designed to turn visitors into customers.',
    features: [
      'Custom design & UI/UX',
      'WordPress builds',
      'Mobile-first responsive',
      'Next.js / React development',
      'SEO-ready architecture',
      'CRO & analytics setup',
    ],
    price: '$3,000 – $15,000+',
    color: '#7c5cff',
    gradient: 'linear-gradient(90deg,#7c5cff,#a07cff)',
  },
  {
    num: '06',
    tags: 'NGOS · CHARITIES · FOUNDATIONS',
    title: 'Non-Profit Management',
    desc: 'Purpose-driven marketing for non-profits and charities. We help mission-led organizations grow their reach, raise donations, and build communities — at rates built for your budget.',
    features: [
      'Donor acquisition campaigns',
      'SEO & content for awareness',
      'Fundraising landing pages',
      'Grant-ready brand storytelling',
      'Social media & email campaigns',
      'Google Ad Grants management',
    ],
    price: 'Special pricing',
    color: '#10b981',
    gradient: 'linear-gradient(90deg,#10b981,#3ed9a4)',
  },
  {
    num: '07',
    tags: 'BRANDING',
    title: 'Branding & Visual Identity',
    desc: 'From brand positioning and tone of voice to visual identity and full brand guidelines. We build brands that stand out and attract the right customers.',
    features: [
      'Brand positioning strategy',
      'Brand guidelines',
      'Marketing collateral',
      'Logo & visual identity',
      'Tone of voice & copywriting',
      'Brand photography direction',
    ],
    price: '$4,000 – $20,000',
    color: '#f5a623',
    gradient: 'linear-gradient(90deg,#f5a623,#ffc85c)',
  },
  {
    num: '08',
    tags: 'FORBES · BUSINESS INSIDER · TECHCRUNCH',
    title: 'PR & Press',
    desc: 'Get featured in Forbes, Business Insider, Entrepreneur, and industry publications. We write and pitch your story to journalists who actually publish.',
    features: [
      'Forbes & Business Insider pitching',
      'HARO / Qwoted monitoring',
      'Podcast booking',
      'Article writing (journalist quality)',
      'Press release writing & distribution',
      'Award submissions',
    ],
    price: 'From $2,000 / mo',
    color: '#ff4d4d',
    gradient: 'linear-gradient(90deg,#ff4d4d,#ff7a7a)',
  },
  {
    num: '09',
    tags: 'MIAMI · NEW YORK · NATIONWIDE',
    title: 'Event Management',
    desc: 'Full-service event production — venue sourcing, speakers, sponsors, DJ, hostess, tech setup, guest lists, email campaigns, and post-event management.',
    features: [
      'Venue sourcing & management',
      'Apollo guest lists & CRM',
      'On-site production & AV',
      'Speaker & sponsor coordination',
      'Email invitations & reminders',
      'Post-event reporting',
    ],
    price: 'Custom pricing',
    color: '#14c4c4',
    gradient: 'linear-gradient(90deg,#14c4c4,#4ee0e0)',
  },
];
