// ─── Solutions page service cards ─────────────────────────────────────────────
// Colours / gradients are taken straight from the reference design - one accent
// per service, reused for the number, tags, bullets and the "GET STARTED" pill.
export const SOLUTIONS = [
  // Hidden: services no longer offered (AI SEO, Social Media Marketing,
  // Meta & Google Ads, Web Design & Development). Uncomment to bring one back.
  // {
  //   num: '01',
  //   tags: 'GOOGLE · CHATGPT · PERPLEXITY · SGE',
  //   title: 'AI SEO',
  //   desc: 'Rank everywhere people search, Google, ChatGPT, Perplexity, and Google AI Overviews. We combine traditional SEO with AI search optimization so your brand gets found and cited across every platform.',
  //   features: [
  //     'Technical SEO audit & fixes',
  //     'Link building',
  //     'AI Overview & Perplexity citations',
  //     'Keyword research & content strategy',
  //     'llms.txt & entity SEO',
  //     'Schema markup & E-E-A-T content',
  //   ],
  //   price: 'Custom pricing',
  //   color: '#1e9bff',
  //   gradient: 'linear-gradient(90deg,#1e9bff,#5bc0ff)',
  //   href: '/seo',
  // },
  // {
  //   num: '02',
  //   tags: 'SMM',
  //   title: 'Social Media Marketing',
  //   desc: 'From organic content creation to influencer marketing. We manage TikTok, Instagram, LinkedIn, and YouTube with data-driven strategies that grow your brand and drive conversions.',
  //   features: [
  //     'Content strategy & calendar',
  //     'Influencer collaboration',
  //     'Trend analysis',
  //     'Creative video production',
  //     'Community management',
  //     'Performance reporting',
  //   ],
  //   price: 'Custom pricing',
  //   color: '#ff4d9d',
  //   gradient: 'linear-gradient(90deg,#ff4d9d,#ff7ab8)',
  //   href: '/social-media',
  // },
  // {
  //   num: '03',
  //   tags: 'PAID ADS',
  //   title: 'Meta & Google Ads',
  //   desc: 'ROI-focused paid ad campaigns. We handle full-funnel strategy, creative production, audience targeting, and continuous optimization across Meta and Google.',
  //   features: [
  //     'Campaign strategy & setup',
  //     'Audience research & targeting',
  //     'Conversion tracking',
  //     'Ad creative production',
  //     'A/B testing',
  //     'Weekly optimization reports',
  //   ],
  //   price: 'Custom pricing',
  //   color: '#ff8c1e',
  //   gradient: 'linear-gradient(90deg,#ff8c1e,#ffb14d)',
  //   href: '/paid-ads',
  // },
  {
    num: '01',
    tags: 'CLAUDE · AI · CHATBOTS',
    title: 'AI Assistants & Automations',
    desc: 'Custom AI assistants deployed on Claude, trained on your business, live 24/7. We handle everything from strategy and build to integration and ongoing optimization.',
    features: [
      'Business needs analysis',
      'Claude / OpenAI deployment',
      'Lead qualification flows',
      'Custom AI assistant design',
      'Platform & CRM integration',
      '24/7 automated support',
    ],
    price: 'Custom pricing',
    color: '#10b981',
    gradient: 'linear-gradient(90deg,#10b981,#3ed9a4)',
    href: '/ai-automation',
  },
  // {
  //   num: '05',
  //   tags: 'NEXT.JS · WORDPRESS · CUSTOM',
  //   title: 'Web Design & Development',
  //   desc: 'High-converting websites built on Next.js, WordPress, or fully custom code. Optimized for speed, SEO, and mobile, designed to turn visitors into customers.',
  //   features: [
  //     'Custom design & UI/UX',
  //     'WordPress builds',
  //     'Mobile-first responsive',
  //     'Next.js / React development',
  //     'SEO-ready architecture',
  //     'CRO & analytics setup',
  //   ],
  //   price: 'Custom pricing',
  //   color: '#7c5cff',
  //   gradient: 'linear-gradient(90deg,#7c5cff,#a07cff)',
  //   href: '/web-development',
  // },
  {
    num: '02',
    tags: 'SAP · BEARINGPOINT · JAGGAER · SALESFORCE',
    title: 'ERP Services',
    desc: 'End-to-end SAP implementation and support, from Finance, Procurement, Production, HR, and Sales to Business Analytics. As KSA’s leading SAP service provider and a BearingPoint partner, we tailor solutions that drive measurable success.',
    features: [
      'SAP implementation & support',
      'Finance, Procurement & HR modules',
      'Sales & Business Analytics',
      'Jaggaer & Salesforce services',
      'AI with Joule, Qlik & ETM.Next',
      'Vendor, customer & government workflows',
    ],
    price: 'Custom pricing',
    color: '#EE4646',
    gradient: 'linear-gradient(90deg,#EE4646,#ff8080)',
    href: '/erp-development',
  },
  {
    num: '03',
    tags: 'CORPORATE FILMS · AI PRESENTERS · SOCIAL',
    title: 'AI Video Production',
    desc: 'AI-produced corporate intros, presentations, explainers and scroll-stopping social videos. Polished, on-brand and delivered fast, in both Arabic and English.',
    features: [
      'Corporate intro & brand films',
      'Presentation & explainer videos',
      'AI presenters & spokespeople',
      'Product & character videos',
      'Social & ad creatives',
      'Multilingual voiceovers (AR & EN)',
    ],
    price: 'Custom pricing',
    color: '#ff4d9d',
    gradient: 'linear-gradient(90deg,#ff4d9d,#ff7ab8)',
    href: '/ai-video',
  },
];
