import { pageMeta } from '@/lib/site';
import LegalPage from '@/components/Legal/LegalPage';

export const metadata = pageMeta({
  title: 'Terms & Conditions',
  description: 'The terms that govern your use of the Safe Hands Digital website and services.',
  path: '/terms',
});

const SECTIONS = [
  {
    heading: 'Acceptance of Terms',
    body: [
      'By accessing or using the Safe Hands Digital website and services, you agree to be bound by these Terms & Conditions. If you do not agree with any part of these terms, please do not use our website or services.',
    ],
  },
  {
    heading: 'Our Services',
    body: [
      'Safe Hands Digital provides engineering services (including MEP engineering, mechanical operation & maintenance, and sp.ICE thermal energy storage), AI assistant and automation solutions, ERP services, AI video production, and related services. The specific scope, deliverables, timelines, and fees for any engagement will be set out in a separate proposal or agreement between you and us.',
      'We reserve the right to modify or discontinue any service, or any part of our website, at any time without prior notice.',
    ],
  },
  {
    heading: 'Proposals & Payment',
    body: [
      'Any quotation or proposal we provide is valid for the period stated within it. Fees, payment schedules, and milestones are governed by the individual agreement for each engagement. Unless otherwise agreed in writing, invoices are payable within the terms stated on the invoice.',
    ],
  },
  {
    heading: 'Client Responsibilities',
    body: [
      'You agree to provide accurate information and any materials, access, or approvals we reasonably need to deliver our services on time. Delays in providing these may affect agreed timelines. You are responsible for ensuring that any content you supply does not infringe the rights of any third party.',
    ],
  },
  {
    heading: 'Intellectual Property',
    body: [
      'All content on this website, including text, graphics, logos, and the Safe Hands brand, is owned by or licensed to Safe Hands Digital and is protected by applicable intellectual property laws. You may not reproduce or reuse it without our written permission.',
      'Ownership of deliverables produced during a paid engagement transfers to the client upon full payment, unless otherwise stated in the relevant agreement. We retain the right to display completed work in our portfolio and marketing.',
    ],
  },
  {
    heading: 'AI Tools & Automated Responses',
    body: [
      'Our website may include AI-powered tools, such as our assistant Maya. Responses generated by these tools are provided for general guidance only, may not always be accurate, and do not constitute a binding offer or professional advice.',
    ],
  },
  {
    heading: 'Limitation of Liability',
    body: [
      'To the fullest extent permitted by law, Safe Hands Digital shall not be liable for any indirect, incidental, or consequential damages arising from your use of our website or services. Our total liability for any claim shall not exceed the amount paid by you for the specific service giving rise to the claim.',
    ],
  },
  {
    heading: 'Third-Party Links',
    body: [
      'Our website may link to third-party websites and platforms. We are not responsible for the content, products, or practices of those sites and do not endorse them.',
    ],
  },
  {
    heading: 'Changes to These Terms',
    body: [
      'We may revise these Terms & Conditions from time to time. The current version will always be posted on this page with an updated revision date. Your continued use of our website after any change constitutes acceptance of the revised terms.',
    ],
  },
  {
    heading: 'Governing Law',
    body: [
      'These Terms & Conditions are governed by and construed in accordance with the laws of the Kingdom of Saudi Arabia, and any disputes shall be subject to the exclusive jurisdiction of the courts of Saudi Arabia.',
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      updated="6 July 2026"
      intro="These terms govern your use of the Safe Hands Digital website and the services we provide. Please read them carefully."
      sections={SECTIONS}
    />
  );
}
